# Generated by Django 5.1 on 2024-08-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=250,
                        null=True,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="название"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="ссылка на обучение"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="план обучения",
                    ),
                ),
                (
                    "study_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="начало обучения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время обновления"
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(to="study.students", verbose_name="студент"),
                ),
            ],
            options={
                "verbose_name": "Обучение",
                "verbose_name_plural": "Обучения",
            },
        ),
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="название лекции"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="содержание"),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="автор контента",
                    ),
                ),
                (
                    "study_materials",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study.study",
                        verbose_name="материалы обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "материал",
                "verbose_name_plural": "материалы",
            },
        ),
    ]
