# Generated by Django 5.1 on 2024-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="students",
            options={"verbose_name": "студент", "verbose_name_plural": "студенты"},
        ),
    ]
