# Generated by Django 5.1 on 2024-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_alter_students_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="student",
            field=models.ManyToManyField(
                blank=True, null=True, to="study.students", verbose_name="студент"
            ),
        ),
    ]
