# Generated by Django 5.1 on 2024-08-15 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_alter_study_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Students",
        ),
        migrations.AlterField(
            model_name="study",
            name="student",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="студент"
            ),
        ),
    ]
