# Generated by Django 5.1 on 2024-08-16 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_delete_students_alter_study_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="student",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
    ]
